### ISSUE TITLE
[Request] Load LLM and clip in 8bit

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [kijai/ComfyUI-HunyuanVideoWrapper#11]
First of all, thank you for your excellent work.

I also tried this node, but I get OOM when loading the model. is it possible to add an option to load in 8bit?

**Comment by kijai** [comment]
Probably, haven't had the time to look into the LLM side of things yet.

**Comment by doogyhatts** [comment]
Is it possible to do a GGUF Q8 for the LLM, similar what city96 had done for t5-v1_1-xxl encoder?

**Comment by CognitiveSourceress** [comment]
So, I barely know enough to try, so I may have been barking up the wrong tree. But I noticed the PRECISION_TO_TYPE constant already had an option for float8_e4m3fn, so I added it to the options for the loader. This appeared to give it the room it needed to run on my GPU, but the transformers implementation uses a lot of operations not supported for FP8.

I was working my way through them by patching those operations directly in transformers, in modeling_llama.py, upcasting to bf16 to get through them, but eventually it looked like the next change I needed to make was in a torch module so I decided since what I was doing was clearly not the proper way to do it, I'd just restore my copy of transformers and report back.

I also tried wrapping the model call in an autocast, but it didn't seem to work. Mighta done it wrong though.

Anyway, not sure if any of this is helpful in any way, but I figured I'd share just in case. If anyone has some advice for what I should be trying to do, I'd be glad to see if I can work my way through it, but like I said, I don't really know what I'm doing.

**Comment by kijai** [comment]
> So, I barely know enough to try, so I may have been barking up the wrong tree. But I noticed the PRECISION_TO_TYPE constant already had an option for float8_e4m3fn, so I added it to the options for the loader. This appeared to give it the room it needed to run on my GPU, but the transformers implementation uses a lot of operations not supported for FP8.
> 
> I was working my way through them by patching those operations directly in transformers, in modeling_llama.py, upcasting to bf16 to get through them, but eventually it looked like the next change I needed to make was in a torch module so I decided since what I was doing was clearly not the proper way to do it, I'd just restore my copy of transformers and report back.
> 
> I also tried wrapping the model call in an autocast, but it didn't seem to work. Mighta done it wrong though.
> 
> Anyway, not sure if any of this is helpful in any way, but I figured I'd share just in case. If anyone has some advice for what I should be trying to do, I'd be glad to see if I can work my way through it, but like I said, I don't really know what I'm doing.

Transformers actually has builtin support to quant on the fly with bitsandbytes, I added the nf4 option for now to test.

**Comment by CognitiveSourceress** [comment]
Thanks! I knew what I was doing was silly and there would be a better way but it was fun to try. I'm able to run it now with the nf4 option. 3060 12GB, 16GB RAM, 15.6s/it at 512, 512, 33, for a total of about 5m:12s per video.

Haven't tried playing around with the settings to see if I can get more out of it yet, but looking at my GPU usage during decoding, I doubt it. Still, this is pretty incredible as it is and I'm sure I can find ways to incorporate it. So thanks again for all your efforts being on top of this stuff and making it accessible.
